kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: icinga-ready-check
subjects:
- kind: ServiceAccount
  name: icinga-ready-check
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: icinga-ready-check
  apiGroup: rbac.authorization.k8s.io
